### ISSUE TITLE
Most test fails on Unexpected command/status ID with sumo 0.32

### ISSUE THREAD

**Issue by stefanobortoli** [egueli/TraCI4J#31]
it.polito.appeal.traci.TraCIException$UnexpectedData: Unexpected command/status ID: expected 164, got 2
	at it.polito.appeal.traci.Utils.checkStatusResponse(Utils.java:57)
	at it.polito.appeal.traci.ChangeStateQuery.pickResponses(ChangeStateQuery.java:83)
	at it.polito.appeal.traci.MultiQuery.run(MultiQuery.java:108)
	at it.polito.appeal.traci.SumoTraciConnection.nextSimStep(SumoTraciConnection.java:622)
	at it.polito.appeal.traci.test.TraCITest.testRefreshedValues(TraCITest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	
in particular, it seems that the nextSimulationStep() method fails on this.

**Comment by blueskych** [comment]
using sumo  0.30.0  will sove this problem

**Comment by stefanobortoli** [comment]
oh, I tried to go back to 0.28 and failed. Then I moved to Traas and I solved my problems. The issue still stands for version 0.32.0
